### ISSUE TITLE
DiaglogueLayer.gd::start_id is not used in start_dialogue_file func 

### ISSUE THREAD

**Issue by ivanskorikov** [leylandpaladin/insane_rpg_dev#11]
```
func start_dialogue_file(target, start_id):
					
	dialogueWindow.load_file("res://Data/Dialogues/%s.json" % [target.obj_name])
	dialogueWindow.start("1")
```
Need to use it in dialogueWindow.start() call. At this stage using a hardcoded value is fine, but later on we should support starting a dialogue from an arbitrary dialogue node.

**Comment by leylandpaladin** [comment]
We won't use this func anymore

**Comment by ivanskorikov** [comment]
@leylandpaladin which commit contains this fix?
